### PR TITLE
Refactor connector shell code and update readme

### PR DESCRIPTION
**Pull request by FabioRosado**
I've decided to bring the work that I was doing in the attempt to merge this connector into core here. 
The code itself it's pretty much the same with a little addition to a logging that tells the user that the connector doesn't work on windows.

The readme was also modified with that note.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
I'm happy for you to merge this whenever you are ready

**Comment by FabioRosado** [comment]
You will have to merge this PR yourself I only have read access to this repo 😄 👍

**Comment by jacobtomlinson** [comment]
You do now :)

**Comment by jacobtomlinson** [comment]
Something's not quite right with this in the end. The tests on the core repo are now failing due to this.

**Comment by FabioRosado** [comment]
I am going to revert these changes (the ones related to the opsdroid pointer). I was testing zonagilreath PR and tox is complaining that only 22% of the code is being tested, which is a bit weird haha

**Pull request merged**
